### ISSUE TITLE
Works nothing like expected

### ISSUE THREAD

**Issue by JuiP** [sugarlabs/maps-activity#13]
Gives an error-

`1585750740.919100 ERROR root: Exception reading icon info: File contains no section headers.
file: /usr/share/icons/Adwaita/48x48/actions/edit-find.png, line: 1
'\x89PNG\r\n'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sugar3/graphics/icon.py", line 212, in _get_attach_points
    cp.readfp(config_file)
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: /usr/share/icons/Adwaita/48x48/actions/edit-find.png, line: 1
'\x89PNG\r\n'
127.0.0.1 - - [01/Apr/2020 19:49:01] "GET /comet.js?t=1585750741066 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:01] "GET /mediaQuery.js?s=21.527359999999994&w=-58.53096&n=74.92063999999999&e=36.39096 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:04] "GET /comet.js?t=1585750741100 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:04] "GET /hideMedia.js?t=1585750744047 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:04] "GET /comet.js?t=1585750744053 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:04] "GET /updateLocation.js?lat=48.40237276438147&lng=-11.686197909463756&z=4&x=-1&y=-1 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:06] "GET /comet.js?t=1585750744157 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:06] "GET /hideMedia.js?t=1585750746296 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:06] "GET /comet.js?t=1585750746305 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:06] "GET /updateLocation.js?lat=48.40237276438147&lng=-11.686197909463756&z=5&x=-1&y=-1 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:06] "GET /comet.js?t=1585750746407 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:06] "GET /hideMedia.js?t=1585750746424 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:06] "GET /comet.js?t=1585750746508 HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2020 19:49:06] "GET /updateLocation.js?lat=48.40237276438147&lng=-11.686197909463756&z=6&x=-1&y=-1 HTTP/1.1" 200 -
`

**Comment by Saumya-Mishra9129** [comment]
@JuiP It would be great if you add steps to reproduce the error.

**Comment by quozl** [comment]
> ```log
> 1585750740.919100 ERROR root: Exception reading icon info: File contains no section headers. file: /usr/share/icons/Adwaita/48x48/actions/edit-find.png, line: 1 '\x89PNG\r\n'
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/sugar3/graphics/icon.py", line 212, in _get_attach_points
>     cp.readfp(config_file)
> File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
>     self._read(fp, filename)
> File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
>     raise MissingSectionHeaderError(fpname, lineno, line)
> MissingSectionHeaderError: File contains no section headers. file: /usr/share/icons/Adwaita/48x48/actions/edit-find.png, line: 1 '\x89PNG\r\n' 
> ```

That's the important part.

Same as https://github.com/sugarlabs/activity-abacus/issues/16.  Was fixed in https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/58224cb15d84765e79492c7bb513e952e856cbfe.  You're using an old release of the toolkit?  Please upgrade.

https://github.com/sugarlabs/maps-activity/blob/41430493e767790361a55832a2fd6a5bb927a401/map.py#L150 is where the edit-find icon is specified.
